var CryptoJS=require("crypto-js");
var BASE="https://api.hlowb.com",PKG="com.external.castle",CHANNEL="IndiaA",CLIENT="1",LANG="en-US";
var TMDB="https://api.themoviedb.org/3",TMDB_KEY="68e094699525b18a70bab2f86b1fa706";
var API_UA="okhttp/4.9.3",PLAYER_UA="Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 Chrome/137 Mobile Safari/537.36";

function clean(v){return v==null?"":String(v).trim()}
function apiHeaders(extra){var h={"User-Agent":API_UA,Accept:"application/json","Accept-Language":"en-US,en;q=0.9",Connection:"Keep-Alive",Referer:BASE};Object.keys(extra||{}).forEach(function(k){h[k]=extra[k]});return h}
function deriveKey(sec){var raw="";try{raw=atob(String(sec||""))}catch(_){}raw=(raw+"T!BgJB").slice(0,16);while(raw.length<16)raw+="\x00";var hex="";for(var i=0;i<raw.length;i++){var x=(raw.charCodeAt(i)&255).toString(16);hex+=x.length<2?"0"+x:x}return CryptoJS.enc.Hex.parse(hex)}
function decryptCastle(cipher,sec){var key=deriveKey(sec);var cp=CryptoJS.lib.CipherParams.create({ciphertext:CryptoJS.enc.Base64.parse(clean(cipher))});var p=CryptoJS.AES.decrypt(cp,key,{iv:key,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7});return CryptoJS.enc.Utf8.stringify(p)}
function safeParse(t){return JSON.parse(String(t||"").replace(/([:{[,]\s*)(\d{16,})/g,'$1"$2"'))}
function unwrap(o){return o&&o.data&&typeof o.data==="object"&&!Array.isArray(o.data)?o.data:o}
function extractCipher(t){var s=clean(t);if(!s)throw new Error("empty Castle response");try{var j=JSON.parse(s);if(j&&typeof j.data==="string")return clean(j.data)}catch(_){}return s}
function requestText(url,opt){opt=opt||{};opt.headers=apiHeaders(opt.headers);return fetch(url,opt).then(function(r){if(!r.ok)throw new Error("Castle HTTP "+r.status);return r.text()})}
function encJson(url,sec,opt){return requestText(url,opt).then(function(t){return unwrap(safeParse(decryptCastle(extractCipher(t),sec)))})}

function tmdbMeta(id,type){var t=type==="tv"?"tv":"movie";return fetch(TMDB+"/"+t+"/"+encodeURIComponent(String(id))+"?api_key="+TMDB_KEY+"&language=en-US",{headers:{Accept:"application/json","User-Agent":PLAYER_UA}}).then(function(r){if(!r.ok)throw new Error("TMDB "+r.status);return r.json()}).then(function(d){var date=clean(t==="tv"?d.first_air_date:d.release_date);return{title:clean(t==="tv"?d.name:d.title),originalTitle:clean(t==="tv"?d.original_name:d.original_title),year:date?parseInt(date.slice(0,4),10)||0:0}})}
function getKey(){return fetch(BASE+"/v0.1/system/getSecurityKey/1?channel="+CHANNEL+"&clientType="+CLIENT+"&lang="+LANG,{headers:apiHeaders()}).then(function(r){if(!r.ok)throw new Error("Castle key "+r.status);return r.json()}).then(function(j){if(!j||Number(j.code)!==200||!j.data)throw new Error("Castle key missing");return clean(j.data)})}
function norm(v){return clean(v).toLowerCase().replace(/[^a-z0-9]+/g,"")}
function yearOf(r){var n=Number(r&&r.publishTime);if(!isFinite(n)||n<=0)return 0;try{return new Date(n).getUTCFullYear()}catch(_){return 0}}
function chooseMatch(rows,meta){if(!Array.isArray(rows)||!rows.length)return null;var a=norm(meta.title),b=norm(meta.originalTitle),y=Number(meta.year)||0;function exact(r){var n=norm(r&&(r.title||r.name));return n&&(n===a||(b&&n===b))}return rows.find(function(r){return exact(r)&&(!y||yearOf(r)===y)})||rows.find(exact)||rows.find(function(r){var n=norm(r&&(r.title||r.name));return n&&a&&(n.indexOf(a)>=0||a.indexOf(n)>=0)&&(!y||yearOf(r)===y)})||rows[0]}
function search(sec,meta){var kw=meta.year?meta.title+" "+meta.year:meta.title;var q=["channel="+CHANNEL,"clientType="+CLIENT,"keyword="+encodeURIComponent(kw),"lang="+LANG,"mode=1","packageName="+encodeURIComponent(PKG),"page=1","size=30"].join("&");return encJson(BASE+"/film-api/v1.1.0/movie/searchByKeyword?"+q,sec).then(function(d){return chooseMatch((d&&d.rows)||[],meta)})}
function detail(sec,id){return encJson(BASE+"/film-api/v1.9.9/movie?channel="+CHANNEL+"&clientType="+CLIENT+"&lang="+LANG+"&movieId="+encodeURIComponent(String(id))+"&packageName="+encodeURIComponent(PKG),sec)}
function video(sec,movieId,episodeId,res,languageId){var body={mode:"1",appMarket:"GuanWang",clientType:CLIENT,woolUser:"false",apkSignKey:"ED0955EB04E67A1D9F3305B95454FED485261475",androidVersion:"13",movieId:String(movieId),episodeId:String(episodeId),isNewUser:"true",resolution:String(res),packageName:PKG};if(languageId!=null)body.languageId=String(languageId);var u=BASE+"/film-api/v2.0.1/movie/getVideo2?clientType="+CLIENT+"&packageName="+encodeURIComponent(PKG)+"&channel="+CHANNEL+"&lang="+LANG;return encJson(u,sec,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})}
function quality(url,fallback){var m=clean(url).match(/\/(2160|1440|1080|720|576|540|480|360|240)(?:\/|_|\.)/i);return m?(m[1]==="2160"?"4K":m[1]+"p"):(fallback||"Auto")}
function pri(t){var n=clean(t&&t.languageName).toLowerCase();if(n==="english")return 0;if(n==="ost"||n.indexOf("original")>=0)return 1;if(n==="hindi")return 2;return 10}
function tracks(list){var a=(Array.isArray(list)?list:[]).filter(function(t){return t&&t.existIndividualVideo===true});if(!a.length)a=(Array.isArray(list)?list:[]).filter(Boolean);a.sort(function(x,y){return pri(x)-pri(y)});return a.slice(0,3)}
function subs(d){return (Array.isArray(d&&d.subtitles)?d.subtitles:[]).filter(function(s){return s&&s.url}).slice(0,8).map(function(s){return{url:String(s.url).replace(/ /g,"%20"),language:clean(s.abbreviate||s.title)||"und",name:(clean(s.title||s.abbreviate)||"Subtitle")+" [Castle]"}})}
function one(data,lang,res){var u=clean(data&&data.videoUrl);if(!/^https?:\/\//i.test(u))return Promise.resolve(null);var fb=res===3?"1080p":res===2?"720p":"480p";var q=quality(u,fb),ln=clean(lang)||"Default",label="CastleTV · "+ln+" · "+q;return fetch(u,{headers:{"User-Agent":PLAYER_UA,Accept:"*/*",Range:"bytes=0-1023"}}).then(function(r){if(!(r.ok||r.status===206))throw new Error("media "+r.status);return{name:label,title:label,url:u,quality:q,language:ln,provider:"stellar-castletv",headers:{"User-Agent":PLAYER_UA,Accept:"*/*"},subtitles:subs(data)}}).catch(function(){return null})}

function episodeCtx(sec,id,type,season,episode){return detail(sec,id).then(function(d){var active=String(id);if(type==="tv"){var se=(Array.isArray(d&&d.seasons)?d.seasons:[]).find(function(x){return Number(x&&x.number)===Number(season||1)});if(se&&se.movieId&&String(se.movieId)!==active){active=String(se.movieId);return detail(sec,active).then(function(dd){return{active:active,d:dd}})}}return{active:active,d:d}}).then(function(c){var eps=Array.isArray(c.d&&c.d.episodes)?c.d.episodes:[];var ep=type==="tv"?eps.find(function(e){return Number(e&&e.number)===Number(episode||1)}):eps[0];if(!ep||!ep.id)throw new Error("episode missing");return{active:c.active,ep:ep}})}

function getStreams(tmdbId,mediaType,season,episode){var meta=null,sec="";return tmdbMeta(tmdbId,mediaType).then(function(m){meta=m;return getKey()}).then(function(k){sec=k;return search(sec,meta)}).then(function(hit){if(!hit)throw new Error("title missing");var id=clean(hit.id||hit.redirectId||hit.redirectIdStr);if(!id)throw new Error("id missing");return episodeCtx(sec,id,mediaType,season,episode)}).then(function(c){var ts=tracks(c.ep.tracks||[]),jobs=[];if(ts.length){ts.forEach(function(t){[3,2,1].forEach(function(r){jobs.push(video(sec,c.active,String(c.ep.id),r,t.languageId).then(function(d){return one(d,t.languageName||t.abbreviate,r)}).catch(function(){return null}))})})}else{[3,2,1].forEach(function(r){jobs.push(video(sec,c.active,String(c.ep.id),r,null).then(function(d){return one(d,"Default",r)}).catch(function(){return null}))})}return Promise.all(jobs)}).then(function(rows){var out=[],seen={};(rows||[]).forEach(function(x){if(!x||!x.url||seen[x.url])return;seen[x.url]=1;out.push(x)});console.log("[Stellar/CastleTV] streams="+out.length);return out}).catch(function(e){console.error("[Stellar/CastleTV] "+(e&&e.message?e.message:e));return[]})}
module.exports={getStreams:getStreams,chooseMatch:chooseMatch,qualityFromUrl:quality,decryptCastle:decryptCastle};
