// NOVIPNOAD Local provider for Nuvio.
// First-party NOVIPNOAD search/detail pages + direct player resolver based on the
// public novipnoad-plugin protocol. Fails closed on ambiguous identity or decode errors.
var SITE_CANDIDATES=["https://www.novipnoad.ca","https://www.novipnoad.uk","https://www.novipnoad.net"];
var PLAYER="https://player.novipnoad.net";
var UA="Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Mobile Safari/537.36";
var FALLBACK_RC4_KEY="ce974576";
function clean(v){return v==null?"":String(v).trim();}
function log(s){try{console.log("[NOVIPNOAD] "+s);}catch(e){}}
function settings(){try{return typeof globalThis!=="undefined"&&globalThis.SCRAPER_SETTINGS||{};}catch(e){return {};}}
function htmlDecode(s){return clean(s).replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&#x27;/gi,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function norm(s){return htmlDecode(s).toLowerCase().replace(/[\u3010\u3011\[\]()（）《》:：·._-]+/g," ").replace(/[^0-9a-z\u00c0-\u024f\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]+/g," ").replace(/\s+/g," ").trim();}
function safeUrl(u){u=clean(u);if(!/^https?:\/\/[^\s"'<>]+$/i.test(u)||u.length>4096)return false;var m=u.match(/^https?:\/\/([^/?#]+)/i),a=m&&m[1];if(!a||a.indexOf("@")>=0||a.charAt(0)==="[")return false;var h=a.split(":")[0].toLowerCase();if(!h||h.indexOf(".")<0||/^(?:localhost|0\.|127\.|10\.|192\.168\.|169\.254\.|172\.(?:1[6-9]|2\d|3[01])\.)/.test(h))return false;return true;}
function abs(u,base){u=htmlDecode(u).replace(/\\\//g,"/");if(u.indexOf("//")===0)u="https:"+u;if(/^https?:\/\//i.test(u))return safeUrl(u)?u:"";if(u.charAt(0)==="/"&&base){var m=base.match(/^(https?:\/\/[^/]+)/);if(m){u=m[1]+u;return safeUrl(u)?u:"";}}return"";}
function headers(ref,json){return{"User-Agent":UA,"Accept":json?"application/json,text/plain,*/*":"text/html,application/xhtml+xml,*/*;q=0.8","Referer":ref||SITE_CANDIDATES[0]+"/"};}
function fetchText(url,h){if(!safeUrl(url))return Promise.reject(new Error("invalid URL"));var o={method:"GET",headers:h||{}};try{o.skipSizeCheck=true;}catch(e){}return fetch(url,o).then(function(r){if(!r||!r.ok)throw new Error("HTTP "+(r?r.status:"unknown"));return r.text();});}
function fetchJson(url,h){return fetchText(url,h).then(function(t){return JSON.parse(t);});}
function tmdbMeta(id,type){var key=clean(settings().tmdbApiKey);if(!key){try{key=clean(globalThis.TMDB_API_KEY);}catch(e){}}if(!key)return Promise.resolve(null);var base="https://api.themoviedb.org/3/"+(type==="tv"?"tv":"movie")+"/"+encodeURIComponent(String(id));var zh=base+"?api_key="+encodeURIComponent(key)+"&language=zh-CN",en=base+"?api_key="+encodeURIComponent(key)+"&language=en-US";return Promise.all([fetchJson(zh,{"Accept":"application/json"}),fetchJson(en,{"Accept":"application/json"})]).then(function(a){var z=a[0]||{},e=a[1]||{},d=clean(e.release_date||e.first_air_date||z.release_date||z.first_air_date);return{zh:clean(z.title||z.name),en:clean(e.title||e.name),original:clean(e.original_title||e.original_name||z.original_title||z.original_name),year:/^\d{4}/.test(d)?d.slice(0,4):""};}).catch(function(err){log("TMDB metadata: "+(err&&err.message||err));return null;});}
function uniq(a){var o=[],seen={};(a||[]).forEach(function(v){v=clean(v);var k=norm(v);if(v&&k&&!seen[k]){seen[k]=1;o.push(v);}});return o;}
function titleHasAny(title,terms){var n=norm(title);for(var i=0;i<terms.length;i++){var q=norm(terms[i]);if(q&&n.indexOf(q)>=0)return true;}return false;}
function parseVideoItems(html,base){var s=clean(html),out=[],re=/<(?:article|div)\b[^>]*class=["'][^"']*\bvideo-item\b[^"']*["'][^>]*>[\s\S]*?<\/(?:article|div)>/ig,m;while((m=re.exec(s))!==null&&out.length<80){var b=m[0],lm=b.match(/<a\b[^>]*href=["']([^"']+)["'][^>]*>/i),tm=b.match(/class=["'][^"']*\bitem-head\b[^"']*["'][\s\S]*?<h3\b[^>]*>([\s\S]*?)<\/h3>/i);if(!lm||!tm)continue;var u=abs(lm[1],base),t=htmlDecode(tm[1]);if(u&&t)out.push({url:u,title:t});}if(out.length)return out;var re2=/<a\b[^>]*href=["']([^"']+)["'][^>]*>[\s\S]{0,2500}?<h3\b[^>]*>([\s\S]*?)<\/h3>/ig;while((m=re2.exec(s))!==null&&out.length<80){var u2=abs(m[1],base),t2=htmlDecode(m[2]);if(u2&&t2&&!out.some(function(x){return x.url===u2;}))out.push({url:u2,title:t2});}return out;}
function episodeInfo(title){var t=clean(title),m;
  m=t.match(/[（(](\d{1,3})\s*集全[）)]|(?:全|共)\s*(\d{1,3})\s*集/i);if(m){var n=parseInt(m[1]||m[2],10),c=[];for(var k=1;k<=n&&k<=100;k++)c.push(k);return{season:1,episodes:c,explicitSeason:false,complete:true};}
  m=t.match(/(?:^|[^0-9])S(\d{1,2})\s*E(\d{1,3})\s*[-~—–至]\s*(?:E)?(\d{1,3})(?:[^0-9]|$)/i);if(m){var a=[],x=parseInt(m[2],10),y=parseInt(m[3],10);for(var i=x;i<=y&&i<x+50;i++)a.push(i);return{season:parseInt(m[1],10),episodes:a,explicitSeason:true};}
  m=t.match(/\bS(\d{1,2})\s*E(\d{1,3})\b/i);if(m)return{season:parseInt(m[1],10),episodes:[parseInt(m[2],10)],explicitSeason:true};
  m=t.match(/(?:^|[^0-9])(\d{1,3})\s*[-~—–至]\s*(\d{1,3})(?:[^0-9]|$)/);if(m){var b=[],p=parseInt(m[1],10),q=parseInt(m[2],10);for(var j=p;j<=q&&j<p+50;j++)b.push(j);return{season:1,episodes:b,explicitSeason:false};}
  m=t.match(/(?:^|[^0-9])(?:E|EP|第)\s*0*(\d{1,3})\s*(?:集)?(?:[^0-9]|$)/i);if(m)return{season:1,episodes:[parseInt(m[1],10)],explicitSeason:false};
  m=t.match(/(?:^|\s|】|\])0*(\d{1,3})(?=\s*(?:\[|〖|【|$))/);if(m)return{season:1,episodes:[parseInt(m[1],10)],explicitSeason:false};
  return{season:1,episodes:[],explicitSeason:false};}
function chooseMovie(items,terms,year){var cand=[];(items||[]).forEach(function(it){if(!/\/movie\//i.test(it.url)||!titleHasAny(it.title,terms))return;var ys=it.title.match(/(?:19|20)\d{2}/g)||[];if(year&&ys.length&&ys.indexOf(year)<0)return;var score=0,nt=norm(it.title);terms.forEach(function(x){var q=norm(x);if(q&&nt.indexOf(q)>=0)score+=q.length;});if(year&&ys.indexOf(year)>=0)score+=1000;cand.push({it:it,score:score});});cand.sort(function(a,b){return b.score-a.score;});if(!cand.length)return null;if(cand.length>1&&cand[0].score===cand[1].score&&cand[0].it.url!==cand[1].it.url)return null;return cand[0].it;}
function chooseTv(items,terms,season,episode){var exact=[],complete=[];(items||[]).forEach(function(it){if(!/\/tv\//i.test(it.url)||!titleHasAny(it.title,terms))return;var ep=episodeInfo(it.title);if(ep.explicitSeason&&ep.season!==season)return;if(season>1&&!ep.explicitSeason)return;if(ep.episodes.indexOf(episode)>=0){exact.push(it);return;}if(ep.complete&&season===1&&ep.episodes.indexOf(episode)>=0)complete.push(it);});var a=exact.length?exact:complete;if(a.length!==1)return null;return a[0];}
function searchOne(base,query){var u=base+"/?s="+encodeURIComponent(query);return fetchText(u,headers(base+"/",false)).then(function(html){if(/Just a moment|challenge-platform|Access denied/i.test(html))throw new Error("challenge");return parseVideoItems(html,base);});}
function discoverDetail(meta,type,season,episode){if(!meta)return Promise.resolve(null);var terms=uniq([meta.zh,meta.en,meta.original]);if(!terms.length)return Promise.resolve(null);var bases=SITE_CANDIDATES.slice(),bi=0;function tryBase(){if(bi>=bases.length)return Promise.resolve(null);var base=bases[bi++],qi=0,all=[];function nextQ(){if(qi>=terms.length){var picked=type==="tv"?chooseTv(all,terms,season,episode):chooseMovie(all,terms,meta.year);if(picked){picked.base=base;return Promise.resolve(picked);}return tryBase();}var q=terms[qi++];return searchOne(base,q).then(function(items){items.forEach(function(it){if(!all.some(function(x){return x.url===it.url;}))all.push(it);});return nextQ();}).catch(function(e){log(base+" search "+q+": "+(e&&e.message||e));return nextQ();});}return nextQ();}return tryBase();}
function parsePlayInfo(html){var m=clean(html).match(/<script[^>]*>\s*window\.playInfo\s*=\s*(\{[\s\S]*?\})\s*;?\s*<\/script>/i);if(!m)m=clean(html).match(/window\.playInfo\s*=\s*(\{[^;]+\})\s*;/i);if(!m)return null;try{return JSON.parse(m[1]);}catch(e){try{var vid=(m[1].match(/["']?vid["']?\s*:\s*["']([^"']*)["']/i)||[])[1]||"",pkey=(m[1].match(/["']?pkey["']?\s*:\s*["']([^"']*)["']/i)||[])[1]||"";return{vid:vid,pkey:pkey};}catch(e2){return null;}}}
function parseEpisodeButtons(html){var out=[],re=/<[^>]+class=["'][^"']*\bmultilink-btn\b[^"']*["'][^>]*data-vid=["']([^"']+)["'][^>]*>([\s\S]*?)<\//ig,m;while((m=re.exec(clean(html)))!==null&&out.length<100){var v=clean(m[1]),label=htmlDecode(m[2]);if(v)out.push({vid:v,label:label});}return out;}
function buttonEpisode(label){var m=clean(label).match(/(?:S(\d{1,2})\s*)?(?:E|EP)?\s*0*(\d{1,3})/i);return m?{season:m[1]?parseInt(m[1],10):1,episode:parseInt(m[2],10)}:null;}
function selectVids(html,playInfo,type,season,episode,pageTitle){var pkey=clean(playInfo&&playInfo.pkey),vid=clean(playInfo&&playInfo.vid);if(!pkey)return[];if(vid){if(type==="tv"){var ei=episodeInfo(pageTitle);if(ei.explicitSeason&&ei.season!==season)return[];if(ei.episodes.length&&ei.episodes.indexOf(episode)<0)return[];if(season>1&&!ei.explicitSeason)return[];}return[{vid:vid,pkey:pkey,label:type==="tv"?("E"+episode):"Main"}];}var btn=parseEpisodeButtons(html);if(type==="movie")return btn.map(function(b,i){return{vid:b.vid,pkey:pkey,label:b.label||("Line "+(i+1))};});var match=[];btn.forEach(function(b){var e=buttonEpisode(b.label);if(e&&e.episode===episode&&(season===1||e.season===season))match.push({vid:b.vid,pkey:pkey,label:b.label||("E"+episode)});});if(match.length===1)return match;if(!match.length&&season===1&&episode>=1&&episode<=btn.length){var b=btn[episode-1];return[{vid:b.vid,pkey:pkey,label:b.label||("E"+episode)}];}return[];}
function parseVKeyText(s){s=clean(s);var m=s.match(/sessionStorage\.setItem\(\s*(["'])vkey\1\s*,\s*(["'])(\{[\s\S]*?\})\2\s*\)/i);if(m){try{return JSON.parse(m[3]);}catch(e){}}m=s.match(/\{\s*ckey\s*:\s*["'](\w+)["']\s*,\s*ref\s*:\s*["'](.*?)["']\s*,\s*ip\s*:\s*["'](.*?)["']\s*,\s*time\s*:\s*["'](\d+)["']\s*\}/i);return m?{ckey:m[1],ref:m[2],ip:m[3],time:m[4]}:null;}
function parseVKeyObfuscated(js){var direct=parseVKeyText(js);if(direct)return direct;var m2=js.match(/var\s+[A-Za-z_$][\w$]*=\[(\[[0-9,\[\]]+\])\];/),m1=js.match(/var\s+[A-Za-z_$][\w$]*=\s*\[([\d,]+)\];/);if(m2&&m1){try{var arr=JSON.parse("["+m2[1].replace(/,$/,"")+"]"),keys=m1[1].split(",").map(Number),str="";if(arr.length===keys.length){arr.forEach(function(a,i){a.forEach(function(v){str+=String.fromCharCode(v^keys[i]);});});direct=parseVKeyText(str);if(direct)return direct;}}catch(e){}}if(m1){var nums=m1[1].split(",").map(Number),ab=js.match(/var\s+[A-Za-z_$][\w$]*=(\d+),*[A-Za-z_$][\w$]*=(\d+);var\s+[A-Za-z_$][\w$]*='';/);if(ab){var x=parseInt(ab[1],10),d=parseInt(ab[2],10),s1=nums.map(function(v){return String.fromCharCode((v-d)^x);}).join("");direct=parseVKeyText(s1);if(direct)return direct;}var aa=js.match(/var\s+[A-Za-z_$][\w$]*=(\d+);var\s+[A-Za-z_$][\w$]*='';/);if(aa){var k=parseInt(aa[1],10),s2=nums.map(function(v){return String.fromCharCode(v^k);}).join("");direct=parseVKeyText(s2);if(direct)return direct;}}var chunks=[],cr=/[A-Za-z_$][\w$]*\+='([A-Za-z0-9+/=]+)'\+[A-Za-z_$][\w$]*;/g,cm;while((cm=cr.exec(js))!==null)chunks.push(cm[1]);if(chunks.length){try{var raw=atob(chunks.join("")),vals=raw.split(",").map(Number),vr=/var\s+([A-Za-z_$][\w$]*)=([0-9()+\-*/%<>&|^!~]+);/g,vm,args={};while((vm=vr.exec(js))!==null){var ex=vm[2];if(!/^[0-9()+\-*/%<>&|^!~]+$/.test(ex))continue;try{args[vm[1]]=Number(Function('"use strict";return ('+ex+');')());}catch(e){}}var de=js.match(/var\s+[A-Za-z_$][\w$]*=\([A-Za-z_$][\w$]*-([A-Za-z_$][\w$]*)\)\^([A-Za-z_$][\w$]*)\^\(\([A-Za-z_$][\w$]*\*([A-Za-z_$][\w$]*)\)%256\);/);if(de&&args[de[1]]!=null&&args[de[2]]!=null&&args[de[3]]!=null){var a0=args[de[1]],a1=args[de[2]],a2=args[de[3]],s3=vals.map(function(v,i){return String.fromCharCode((v-a0)^a1^((i*a2)%256));}).join("");direct=parseVKeyText(s3);if(direct)return direct;}}catch(e){}}return null;}
function b64bytes(s){var b=atob(clean(s)),a=[];for(var i=0;i<b.length;i++)a.push(b.charCodeAt(i)&255);return a;}
function rc4(key,data){var S=[],j=0,i;for(i=0;i<256;i++)S[i]=i;for(i=0;i<256;i++){j=(j+S[i]+key.charCodeAt(i%key.length))&255;var t=S[i];S[i]=S[j];S[j]=t;}var out=[],x=0,y=0;for(i=0;i<data.length;i++){x=(x+1)&255;y=(y+S[x])&255;var z=S[x];S[x]=S[y];S[y]=z;out.push(data[i]^S[(S[x]+S[y])&255]);}return out;}
function bytesToLatin1(a){var s="";for(var i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return s;}
function queryUrl(base,obj){var q=[],sep=base.indexOf("?")>=0?"&":"?";Object.keys(obj).forEach(function(k){q.push(encodeURIComponent(k)+"="+encodeURIComponent(obj[k]));});return base+sep+q.join("&");}
function resolveVid(v,pkey,detailUrl,siteBase){var p1=PLAYER+"/v1/?url="+encodeURIComponent(v)+"&pkey="+encodeURIComponent(pkey)+"&ref="+encodeURIComponent(detailUrl);return fetchText(p1,headers(siteBase+"/",false)).then(function(h1){var dm=h1.match(/params\[['"]device['"]\]\s*=\s*['"](\w+)['"]/i);if(!dm)throw new Error("device not found");var marker="/*-- 浏览器完整性检查 --*/",part=h1.indexOf(marker)>=0?h1.slice(h1.indexOf(marker)+marker.length):h1;part=part.split("</script>")[0];var vk=parseVKeyObfuscated(part)||parseVKeyObfuscated(h1);if(!vk||!vk.ckey||!vk.time)throw new Error("vkey decode failed");var p2=PLAYER+"/v1/player.php?id="+encodeURIComponent(v)+"&device="+encodeURIComponent(dm[1]);return fetchText(p2,headers(p1,false)).then(function(h2){var jm=h2.match(/const\s+jsapi\s*=\s*['"](.*?)['"]\s*;/i);if(!jm)throw new Error("jsapi not found");var ju=queryUrl(jm[1],{ckey:String(vk.ckey).toUpperCase(),ref:vk.ref||"",ip:vk.ip||"",time:vk.time||""});return fetchText(ju,headers(PLAYER+"/",false)).then(function(js){var em=js.match(/var\s+videoUrl\s*=\s*JSON\.decrypt\(\s*['"](.*?)['"]\s*\)\s*;/i);if(!em)throw new Error("encrypted videoUrl not found");var dec=bytesToLatin1(rc4(FALLBACK_RC4_KEY,b64bytes(em[1]))),obj=JSON.parse(dec);return obj&&Array.isArray(obj.quality)?obj.quality:[];});});});}
function streamType(u,t){var s=clean(t).toLowerCase(),p=clean(u).split(/[?#]/)[0].toLowerCase();if(s.indexOf("m3u8")>=0||/\.m3u8$/.test(p))return"hls";if(s.indexOf("mp4")>=0||/\.mp4$/.test(p))return"mp4";if(s.indexOf("mpd")>=0||/\.mpd$/.test(p))return"dash";return"";}
function qualityName(q){var n=clean(q&&q.name);if(n)return n;var u=clean(q&&q.url),m=u.match(/(?:^|[^0-9])(2160|1440|1080|720|480|360)p?(?:[^0-9]|$)/i);return m?m[1]+"p":"Auto";}
function getStreams(id,mediaType,season,episode){var type=mediaType==="tv"?"tv":"movie",tmdb=clean(id);if(!/^\d+$/.test(tmdb))return Promise.resolve([]);season=parseInt(season,10)||1;episode=parseInt(episode,10)||1;return tmdbMeta(tmdb,type).then(function(meta){if(!meta){log("TMDB metadata unavailable");return[];}return discoverDetail(meta,type,season,episode).then(function(hit){if(!hit){log("no unambiguous NOVIPNOAD match");return[];}return fetchText(hit.url,headers(hit.base+"/",false)).then(function(html){var title=htmlDecode((html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]||hit.title),pi=parsePlayInfo(html),vids=selectVids(html,pi,type,season,episode,title);if(!vids.length){log("no unambiguous vid for "+title);return[];}return Promise.all(vids.slice(0,12).map(function(vd){return resolveVid(vd.vid,vd.pkey,hit.url,hit.base).then(function(qs){return(qs||[]).map(function(q){var u=clean(q.url),st=streamType(u,q.type);if(!safeUrl(u)||!st)return null;var qn=qualityName(q),name="NOVIPNOAD · "+(vd.label||"Line")+" · "+qn;return{name:name,title:name,url:u,quality:qn,type:st,provider:"novipnoad-local",headers:{"User-Agent":UA,"Origin":PLAYER,"Referer":PLAYER+"/"},subtitles:[]};}).filter(Boolean);}).catch(function(e){log("resolve "+vd.label+": "+(e&&e.message||e));return[];});})).then(function(groups){var out=[],seen={};[].concat.apply([],groups).forEach(function(r){if(r&&!seen[r.url]){seen[r.url]=1;out.push(r);}});log(type+" "+tmdb+" matched "+hit.url+" streams="+out.length);return out;});}).catch(function(e){log("detail: "+(e&&e.message||e));return[];});});});}
function onSettings(){return[{type:"header",label:"NOVIPNOAD Local · alpha"},{type:"info",label:"Uses NOVIPNOAD first-party search/detail pages and the public player protocol. .ca is tried first, then .uk/.net. Ambiguous title/episode matches and player-decode failures return zero streams rather than a wrong video."},{type:"text",key:"tmdbApiKey",label:"TMDB API key (used only if Nuvio does not expose a shared TMDB key)",defaultValue:"",isPassword:true}];}
module.exports={getStreams:getStreams,onSettings:onSettings};
