// NoctraTV · OneTouchTV / Atlas
// Current dedicated /mplayer/onetouchtv/resolve flow with ephemeral MZone v2 playback session.
// No embedded API key. Returns validated HLS/DASH/MP4 only.

var BASE="https://api.m-zone.org";
var ORIGIN="https://noctratv.com";
var REFERER="https://onetouchtv.xyz/";
var UA="Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/143 Mobile Safari/537.36";
var SESSION=null,PENDING=null;

function c(v){return v==null?"":String(v).trim();}
function wait(p,ms,n){return new Promise(function(ok,no){var d=false,t=setTimeout(function(){if(!d){d=true;no(new Error(n+" timeout"));}},ms);Promise.resolve(p).then(function(v){if(!d){d=true;clearTimeout(t);ok(v);}},function(e){if(!d){d=true;clearTimeout(t);no(e);}});});}
function b64(a){a=a instanceof Uint8Array?a:new Uint8Array(a||0);var s="";for(var i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function rawSig(a){a=a instanceof Uint8Array?a:new Uint8Array(a||0);if(a.length===64)return a;if(a.length<8||a[0]!==48)throw new Error("ECDSA format");var p=1,l=a[p++];if(l&128){var n=l&127;l=0;while(n--)l=(l<<8)|a[p++];}if(a[p++]!==2)throw new Error("ECDSA r");var rl=a[p++],r=a.slice(p,p+rl);p+=rl;if(a[p++]!==2)throw new Error("ECDSA s");var sl=a[p++],s=a.slice(p,p+sl);while(r.length>32&&r[0]===0)r=r.slice(1);while(s.length>32&&s[0]===0)s=s.slice(1);var out=new Uint8Array(64);out.set(r,32-r.length);out.set(s,64-s.length);return out;}
function h(extra){var x={"User-Agent":UA,Origin:ORIGIN,Referer:ORIGIN+"/",Accept:"application/json,text/plain,*/*"};Object.keys(extra||{}).forEach(function(k){x[k]=String(extra[k]);});return x;}
function fp(){var n=typeof navigator!=="undefined"?navigator:{},s=typeof screen!=="undefined"?screen:{},tz="Asia/Shanghai";try{tz=Intl.DateTimeFormat().resolvedOptions().timeZone||tz;}catch(_){}return{webdriver:false,languages:Array.isArray(n.languages)?n.languages.slice(0,8):["en-US","en"],plugins:Math.min(100,n.plugins&&n.plugins.length?n.plugins.length:5),hardwareConcurrency:Number(n.hardwareConcurrency||8),deviceMemory:Number(n.deviceMemory||8),maxTouchPoints:Number(n.maxTouchPoints||5),platform:c(n.userAgentData&&n.userAgentData.platform)||c(n.platform)||"Android",brands:n.userAgentData&&Array.isArray(n.userAgentData.brands)?n.userAgentData.brands.slice(0,8):[{brand:"Chromium",version:"143"}],mobile:n.userAgentData?!!n.userAgentData.mobile:true,timezone:tz,screen:{width:Number(s.width||1080),height:Number(s.height||2400),colorDepth:Number(s.colorDepth||24),pixelRatio:Number(typeof devicePixelRatio!=="undefined"?devicePixelRatio:2.75)},visibilityState:typeof document!=="undefined"?c(document.visibilityState)||"visible":"visible"};}
function active(s){return!!(s&&s.token&&s.sessionId&&Number(s.expiresAt)>Date.now()+30000);}
function createSession(){if(!globalThis.crypto||!crypto.subtle)return Promise.reject(new Error("WebCrypto unavailable"));var ch,kp;return wait(fetch(BASE+"/api/player/v2/challenge",{cache:"no-store",credentials:"include",headers:h()}),8000,"challenge").then(function(r){if(!r.ok)throw new Error("challenge HTTP "+r.status);return r.json();}).then(function(j){if(!j||!j.challengeId||!j.nonce||!j.issuedAt)throw new Error("bad challenge");ch=j;return crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]);}).then(function(k){kp=k;return Promise.all([crypto.subtle.exportKey("jwk",k.publicKey),crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},k.privateKey,new TextEncoder().encode(ch.challengeId+"."+ch.nonce+"."+ch.issuedAt))]);}).then(function(v){return wait(fetch(BASE+"/api/player/v2/session",{method:"POST",cache:"no-store",credentials:"include",headers:h({"Content-Type":"application/json"}),body:JSON.stringify({challengeId:ch.challengeId,nonce:ch.nonce,publicKey:v[0],signature:b64(rawSig(new Uint8Array(v[1]))),fingerprint:fp(),embedded:false,embedOrigin:"",sandboxed:false,turnstileToken:"",supportsEncryptedTransport:false,supportsEncryptedCapabilities:false,transportPublicKey:null,playerVersion:"mplayer-web-v2",playbackSessionVersion:2,capabilities:["hls","dash","codec-avc"]})}),10000,"session");}).then(function(r){return r.json().catch(function(){return{};}).then(function(j){if(r.status===428&&j.challengeRequired)throw new Error("Turnstile required");if(!r.ok||!j.token||!j.sessionId||!j.expiresAt)throw new Error(c(j.error)||("session HTTP "+r.status));return{token:String(j.token),sessionId:String(j.sessionId),expiresAt:Number(j.expiresAt)};});});}
function session(){if(active(SESSION))return Promise.resolve(SESSION);if(PENDING)return PENDING;PENDING=createSession().then(function(s){SESSION=s;return s;}).finally(function(){PENDING=null;});return PENDING;}
function lease(u,t){try{var x=new URL(u,BASE);if(/(^|\.)m-zone\.org$/i.test(x.hostname)&&!x.searchParams.has("mz_lease"))x.searchParams.set("mz_lease",t);return x.toString();}catch(_){return u;}}
function safeHeaders(o){var x={};Object.keys(o||{}).forEach(function(k){var v=c(o[k]);if(v&&!/^(?:host|connection|content-length|origin)$/i.test(k))x[k]=v;});if(!x.Referer&&!x.referer)x.Referer=REFERER;return x;}
function proxy(raw,kind,hh,s){var u=c(raw);try{var x=new URL(u,BASE);if(/(^|\.)m-zone\.org$/i.test(x.hostname))return lease(x.toString(),s.token);}catch(_){}var p=new URL(BASE+(kind==="dash"?"/dash-proxy":"/m3u8-proxy"));p.searchParams.set("url",u);if(kind!=="dash"){p.searchParams.set("_px","originless-2");p.searchParams.set("_provider","onetouchtv");}if(hh&&Object.keys(hh).length)p.searchParams.set("headers",JSON.stringify(hh));p.searchParams.set("mz_lease",s.token);return p.toString();}
function subProxy(raw,hh,s){var u=c(raw);if(!/^https?:\/\//i.test(u))return"";var p=new URL(BASE+"/subtitle-proxy");p.searchParams.set("url",u);if(hh&&Object.keys(hh).length)p.searchParams.set("headers",JSON.stringify(hh));p.searchParams.set("mz_lease",s.token);return p.toString();}
function subs(tracks,s){var seen={},out=[];(Array.isArray(tracks)?tracks:[]).forEach(function(x){var raw=c(x&&(x.file||x.url));if(!raw)return;var u=subProxy(raw,safeHeaders(x&&x.headers),s);if(!u||seen[u])return;seen[u]=1;var l=c(x&&(x.code||x.label||x.language))||"Subtitle";out.push({url:u,language:l,name:l+" [Atlas]"});});return out.slice(0,24);}
function first(body,base){var a=String(body||"").split(/\r?\n/);for(var i=0;i<a.length;i++){var x=a[i].trim();if(x&&x.charAt(0)!=="#"){try{return new URL(x,base).toString();}catch(_){return"";}}}return"";}
function hq(body){var re=/RESOLUTION=\d+x(\d+)/ig,m,max=0;while((m=re.exec(String(body||"")))!==null)max=Math.max(max,Number(m[1])||0);return max>=2160?"2160p":max>=1440?"1440p":max>=1080?"1080p":max>=720?"720p":max>=480?"480p":"Auto";}
function verifyHls(u){return wait(fetch(u,{cache:"no-store"}),12000,"HLS").then(function(r){if(!r.ok)throw new Error("HLS HTTP "+r.status);var b=r.url||u;return r.text().then(function(t){return{t:t,b:b};});}).then(function(x){if(x.t.trim().indexOf("#EXTM3U")!==0)throw new Error("not HLS");var f=first(x.t,x.b);if(!f)throw new Error("empty HLS");return wait(fetch(f,{cache:"no-store",headers:{Range:"bytes=0-65535"}}),10000,"segment").then(function(r){if(!(r.ok||r.status===206))throw new Error("segment HTTP "+r.status);var ct=c(r.headers.get("content-type")).toLowerCase();if(/text\/html|application\/json/.test(ct))throw new Error("segment not media");return hq(x.t);});});}
function verifyDash(u){return wait(fetch(u,{cache:"no-store"}),12000,"DASH").then(function(r){if(!r.ok)throw new Error("DASH HTTP "+r.status);return r.text();}).then(function(t){if(!/<MPD\b/i.test(t))throw new Error("not DASH");return"Auto";});}
function verifyMp4(u,hh){return wait(fetch(u,{cache:"no-store",headers:Object.assign({},hh,{Range:"bytes=0-65535"})}),12000,"MP4").then(function(r){if(!(r.ok||r.status===206))throw new Error("MP4 HTTP "+r.status);var ct=c(r.headers.get("content-type")).toLowerCase();if(/text\/html|application\/json/.test(ct))throw new Error("not media");return"Auto";});}
function resolve(id,type,season,episode,s){var body={type:type==="tv"?"tv":"movie",tmdbId:String(id)};if(type==="tv"){body.season=String(Number(season||1));body.episode=String(Number(episode||1));}return wait(fetch(BASE+"/mplayer/onetouchtv/resolve",{method:"POST",cache:"no-store",credentials:"include",headers:h({"Content-Type":"application/json","X-MZone-Playback-Lease":s.token,"X-MZone-Relay-Affinity":"https://relay-a.m-zone.org"}),body:JSON.stringify(body)}),20000,"Atlas resolver").then(function(r){return r.json().catch(function(){return{};}).then(function(j){if(!r.ok||!j||j.success===false||!j.result)throw new Error(c(j&&j.error)||("resolver HTTP "+r.status));return j;});});}
function row(u,q,type,server,hh,sb){var n="NoctraTV · OneTouchTV / Atlas · "+server+" · "+q;return{name:n,title:n,url:u,quality:q,type:type,provider:"noctra-onetouchtv",headers:hh||{},subtitles:sb||[]};}
function convert(j,s){var r=j.result||{},raw=c(r.url||r.playlist||r.file);if(!raw)throw new Error("Atlas returned no media URL");var f=c(r.format||r.type).toLowerCase();if(f==="mpd")f="dash";if(f!=="dash"&&f!=="mp4")f="hls";var hh=safeHeaders(r.headers),sb=subs(r.tracks,s),server=c(j.server||r.server)||"primary",q=c(r.maxHeight)?c(r.maxHeight)+"p":"Auto";if(f==="hls"){var u=proxy(raw,"hls",hh,s);return verifyHls(u).then(function(v){return[row(u,q==="Auto"?v:q,"hls",server,{},sb)];});}if(f==="dash"){var d=proxy(raw,"dash",hh,s);return verifyDash(d).then(function(v){return[row(d,q==="Auto"?v:q,"dash",server,{},sb)];});}return verifyMp4(raw,hh).then(function(v){return[row(raw,q==="Auto"?v:q,"mp4",server,hh,sb)];});}
function getStreams(id,type,season,episode){if(!id||(type!=="movie"&&type!=="tv"))return Promise.resolve([]);if(type==="tv"&&(!season||!episode))return Promise.resolve([]);return session().then(function(s){return resolve(id,type,season,episode,s).then(function(j){return convert(j,s);});}).then(function(a){console.log("[Noctra/Atlas] streams="+a.length);return a;}).catch(function(e){console.log("[Noctra/Atlas] "+(e&&e.message?e.message:e));return[];});}
module.exports={getStreams:getStreams};
