// NoctraTV · Videasy CDN / Nova
// Current dedicated /mplayer/videasy/resolve flow, preferredProvider=neon2.
// Uses NoctraTV /tmdb proxy (no embedded key) and ephemeral MZone v2 session.
// Mirrors current MPlayer behavior: HLS and fallback MP4 URLs are relayed through /m3u8-proxy.

var BASE="https://api.m-zone.org";
var ORIGIN="https://noctratv.com";
var REFERER="https://player.videasy.to/";
var UA="Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/143 Mobile Safari/537.36";
var SESSION=null,PENDING=null;

function c(v){return v==null?"":String(v).trim();}
function wait(p,ms,n){return new Promise(function(ok,no){var d=false,t=setTimeout(function(){if(!d){d=true;no(new Error(n+" timeout"));}},ms);Promise.resolve(p).then(function(v){if(!d){d=true;clearTimeout(t);ok(v);}},function(e){if(!d){d=true;clearTimeout(t);no(e);}});});}
function b64(a){a=a instanceof Uint8Array?a:new Uint8Array(a||0);var s="";for(var i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function rawSig(a){a=a instanceof Uint8Array?a:new Uint8Array(a||0);if(a.length===64)return a;if(a.length<8||a[0]!==48)throw new Error("ECDSA format");var p=1,l=a[p++];if(l&128){var n=l&127;l=0;while(n--)l=(l<<8)|a[p++];}if(a[p++]!==2)throw new Error("ECDSA r");var rl=a[p++],r=a.slice(p,p+rl);p+=rl;if(a[p++]!==2)throw new Error("ECDSA s");var sl=a[p++],s=a.slice(p,p+sl);while(r.length>32&&r[0]===0)r=r.slice(1);while(s.length>32&&s[0]===0)s=s.slice(1);var o=new Uint8Array(64);o.set(r,32-r.length);o.set(s,64-s.length);return o;}
function h(extra){var x={"User-Agent":UA,Origin:ORIGIN,Referer:ORIGIN+"/",Accept:"application/json,text/plain,*/*"};Object.keys(extra||{}).forEach(function(k){x[k]=String(extra[k]);});return x;}
function fp(){var n=typeof navigator!=="undefined"?navigator:{},s=typeof screen!=="undefined"?screen:{},tz="Asia/Shanghai";try{tz=Intl.DateTimeFormat().resolvedOptions().timeZone||tz;}catch(_){}return{webdriver:false,languages:Array.isArray(n.languages)?n.languages.slice(0,8):["en-US","en"],plugins:Math.min(100,n.plugins&&n.plugins.length?n.plugins.length:5),hardwareConcurrency:Number(n.hardwareConcurrency||8),deviceMemory:Number(n.deviceMemory||8),maxTouchPoints:Number(n.maxTouchPoints||5),platform:c(n.userAgentData&&n.userAgentData.platform)||c(n.platform)||"Android",brands:n.userAgentData&&Array.isArray(n.userAgentData.brands)?n.userAgentData.brands.slice(0,8):[{brand:"Chromium",version:"143"}],mobile:n.userAgentData?!!n.userAgentData.mobile:true,timezone:tz,screen:{width:Number(s.width||1080),height:Number(s.height||2400),colorDepth:Number(s.colorDepth||24),pixelRatio:Number(typeof devicePixelRatio!=="undefined"?devicePixelRatio:2.75)},visibilityState:typeof document!=="undefined"?c(document.visibilityState)||"visible":"visible"};}
function active(s){return!!(s&&s.token&&s.sessionId&&Number(s.expiresAt)>Date.now()+30000);}
function createSession(){if(!globalThis.crypto||!crypto.subtle)return Promise.reject(new Error("WebCrypto unavailable"));var ch,kp;return wait(fetch(BASE+"/api/player/v2/challenge",{cache:"no-store",credentials:"include",headers:h()}),8000,"challenge").then(function(r){if(!r.ok)throw new Error("challenge HTTP "+r.status);return r.json();}).then(function(j){if(!j||!j.challengeId||!j.nonce||!j.issuedAt)throw new Error("bad challenge");ch=j;return crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]);}).then(function(k){kp=k;return Promise.all([crypto.subtle.exportKey("jwk",k.publicKey),crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},k.privateKey,new TextEncoder().encode(ch.challengeId+"."+ch.nonce+"."+ch.issuedAt))]);}).then(function(v){return wait(fetch(BASE+"/api/player/v2/session",{method:"POST",cache:"no-store",credentials:"include",headers:h({"Content-Type":"application/json"}),body:JSON.stringify({challengeId:ch.challengeId,nonce:ch.nonce,publicKey:v[0],signature:b64(rawSig(new Uint8Array(v[1]))),fingerprint:fp(),embedded:false,embedOrigin:"",sandboxed:false,turnstileToken:"",supportsEncryptedTransport:false,supportsEncryptedCapabilities:false,transportPublicKey:null,playerVersion:"mplayer-web-v2",playbackSessionVersion:2,capabilities:["hls","dash","codec-avc"]})}),10000,"session");}).then(function(r){return r.json().catch(function(){return{};}).then(function(j){if(r.status===428&&j.challengeRequired)throw new Error("Turnstile required");if(!r.ok||!j.token||!j.sessionId||!j.expiresAt)throw new Error(c(j.error)||("session HTTP "+r.status));return{token:String(j.token),sessionId:String(j.sessionId),expiresAt:Number(j.expiresAt)};});});}
function session(){if(active(SESSION))return Promise.resolve(SESSION);if(PENDING)return PENDING;PENDING=createSession().then(function(s){SESSION=s;return s;}).finally(function(){PENDING=null;});return PENDING;}
function meta(id,type){var t=type==="tv"?"tv":"movie",u=BASE+"/tmdb/"+t+"/"+encodeURIComponent(String(id))+"?language=en-US&append_to_response=external_ids";return wait(fetch(u,{cache:"no-store",headers:{Accept:"application/json","User-Agent":UA}}),8000,"metadata").then(function(r){if(!r.ok)throw new Error("metadata HTTP "+r.status);return r.json();}).then(function(j){var title=t==="tv"?(j.name||j.original_name||""):(j.title||j.original_title||""),date=t==="tv"?(j.first_air_date||""):(j.release_date||"");return{title:c(title),year:/^\d{4}/.test(date)?date.slice(0,4):"",imdbId:c(j.imdb_id||(j.external_ids&&j.external_ids.imdb_id))};});}
function lease(u,t){try{var x=new URL(u,BASE);if(/(^|\.)m-zone\.org$/i.test(x.hostname)&&!x.searchParams.has("mz_lease"))x.searchParams.set("mz_lease",t);return x.toString();}catch(_){return u;}}
function relay(raw,slot,s){var u=c(raw);if(!u)return"";try{var x=new URL(u,BASE);if(/(^|\.)m-zone\.org$/i.test(x.hostname))return lease(x.toString(),s.token);}catch(_){}var p=new URL(BASE+"/m3u8-proxy");p.searchParams.set("url",u);p.searchParams.set("_px","originless-2");p.searchParams.set("headers",JSON.stringify({Referer:REFERER}));if(Number.isInteger(Number(slot)))p.searchParams.set("_isp",String(Number(slot)));p.searchParams.set("mz_lease",s.token);return p.toString();}
function subProxy(raw,slot,s){var u=c(raw);if(!/^https?:\/\//i.test(u))return"";var p=new URL(BASE+"/subtitle-proxy");p.searchParams.set("url",u);p.searchParams.set("headers",JSON.stringify({Referer:REFERER}));if(Number.isInteger(Number(slot)))p.searchParams.set("_isp",String(Number(slot)));p.searchParams.set("mz_lease",s.token);return p.toString();}
function subs(a,slot,s){var seen={},out=[];(Array.isArray(a)?a:[]).forEach(function(x){var raw=c(x&&(x.url||x.file));if(!raw)return;var u=subProxy(raw,slot,s);if(!u||seen[u])return;seen[u]=1;var l=c(x&&(x.language||x.lang||x.code||x.label||x.display))||"Subtitle";out.push({url:u,language:l,name:l+" [Nova]"});});return out.slice(0,24);}
function q(v){var m=c(v).match(/(2160|1440|1080|720|576|540|480|360)p?/i);return m?m[1]+"p":"Auto";}
function first(body,base){var a=String(body||"").split(/\r?\n/);for(var i=0;i<a.length;i++){var x=a[i].trim();if(x&&x.charAt(0)!=="#"){try{return new URL(x,base).toString();}catch(_){return"";}}}return"";}
function hq(body){var re=/RESOLUTION=\d+x(\d+)/ig,m,max=0;while((m=re.exec(String(body||"")))!==null)max=Math.max(max,Number(m[1])||0);return max>=2160?"2160p":max>=1440?"1440p":max>=1080?"1080p":max>=720?"720p":max>=480?"480p":"Auto";}
function verifyHls(u){return wait(fetch(u,{cache:"no-store"}),12000,"HLS").then(function(r){if(!r.ok)throw new Error("HLS HTTP "+r.status);var b=r.url||u;return r.text().then(function(t){return{t:t,b:b};});}).then(function(x){if(x.t.trim().indexOf("#EXTM3U")!==0)throw new Error("not HLS");var f=first(x.t,x.b);if(!f)throw new Error("empty HLS");return wait(fetch(f,{cache:"no-store",headers:{Range:"bytes=0-65535"}}),10000,"segment").then(function(r){if(!(r.ok||r.status===206))throw new Error("segment HTTP "+r.status);var ct=c(r.headers.get("content-type")).toLowerCase();if(/text\/html|application\/json/.test(ct))throw new Error("segment not media");return hq(x.t);});});}
function verifyFile(u){return wait(fetch(u,{cache:"no-store",headers:{Range:"bytes=0-65535"}}),12000,"file").then(function(r){if(!(r.ok||r.status===206))throw new Error("file HTTP "+r.status);var ct=c(r.headers.get("content-type")).toLowerCase();if(/text\/html|application\/json/.test(ct))throw new Error("not media");return"Auto";});}
function resolve(m,id,type,season,episode,s){var b={title:m.title,type:type==="tv"?"tv":"movie",year:String(m.year||""),imdbId:m.imdbId||"",tmdbId:String(id),preferredProvider:"neon2",strictProvider:true,audioLanguage:"original"};if(type==="tv"){b.season=String(Number(season||1));b.episode=String(Number(episode||1));}return wait(fetch(BASE+"/mplayer/videasy/resolve",{method:"POST",cache:"no-store",credentials:"include",headers:h({"Content-Type":"application/json","X-MZone-Playback-Lease":s.token,"X-MZone-Relay-Affinity":"https://relay-a.m-zone.org"}),body:JSON.stringify(b)}),20000,"Nova resolver").then(function(r){return r.json().catch(function(){return{};}).then(function(j){if(!r.ok||!j||j.success===false||!j.result)throw new Error(c(j&&j.error)||("resolver HTTP "+r.status));return j;});});}
function row(u,quality,type,server,sb){var n="NoctraTV · Videasy CDN / Nova · "+server+" · "+quality;return{name:n,title:n,url:u,quality:quality,type:type,provider:"noctra-videasy-cdn",headers:{},subtitles:sb||[]};}
function convert(j,s){var r=j.result||{},slot=j.residentialProxySlot,sb=subs(r.subtitles,slot,s),src=Array.isArray(r.sources)?r.sources.filter(function(x){return x&&(x.url||x.file);}):[],server=c(j.provider)||"neon2";var hls=[];src.forEach(function(x){var u=c(x.url||x.file),t=c(x.type).toLowerCase();if(/\.m3u8(?:[?#]|$)/i.test(u)||/hls|mpegurl/.test(t))hls.push(x);});if(hls.length){return Promise.all(hls.slice(0,6).map(function(x,i){var u=relay(x.url||x.file,slot,s),quality=q(x.quality||x.label);return verifyHls(u).then(function(v){return row(u,quality==="Auto"?v:quality,"hls",server,sb);}).catch(function(){return null;});})).then(function(a){var seen={};return a.filter(function(x){if(!x||seen[x.url])return false;seen[x.url]=1;return true;});});}
 var byQ={},order=["4k","1080","720","480","360","unknown"];src.forEach(function(x){var quality=q(x.quality||x.label),k=quality==="2160p"?"4k":quality==="Auto"?"unknown":quality.replace("p","");if(!byQ[k])byQ[k]=x;});return Promise.all(order.filter(function(k){return byQ[k];}).map(function(k){var x=byQ[k],u=relay(x.url||x.file,slot,s),quality=k==="4k"?"2160p":k==="unknown"?"Auto":k+"p";return verifyFile(u).then(function(){return row(u,quality,"mp4",server,sb);}).catch(function(){return null;});})).then(function(a){return a.filter(Boolean);});
}
function getStreams(id,type,season,episode){if(!id||(type!=="movie"&&type!=="tv"))return Promise.resolve([]);if(type==="tv"&&(!season||!episode))return Promise.resolve([]);return Promise.all([meta(id,type),session()]).then(function(v){return resolve(v[0],id,type,season,episode,v[1]).then(function(j){return convert(j,v[1]);});}).then(function(a){console.log("[Noctra/Nova] streams="+a.length);return a;}).catch(function(e){console.log("[Noctra/Nova] "+(e&&e.message?e.message:e));return[];});}
module.exports={getStreams:getStreams};
