var OUTERS=["https://vidapi.xyz","https://streamimdb.ru","https://vidapi.ru","https://vaplayer.ru"];
var UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36";
function clean(v){return v==null?"":String(v).trim();}
function h(ref){var x={"User-Agent":UA,"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Accept-Language":"en-US,en;q=0.5"};if(ref)x.Referer=ref;return x;}
function abs(base,u){try{return new URL(u,base).toString();}catch(e){return u;}}
function embed(base,id,type,season,episode){return type==="tv"?base+"/embed/tv/"+encodeURIComponent(id)+"?s="+encodeURIComponent(season||1)+"&e="+encodeURIComponent(episode||1):base+"/embed/movie/"+encodeURIComponent(id);}
function configFrom(html){var m=String(html||"").match(/const\s+CONFIG\s*=\s*(\{[^;]+\});/);if(!m)return null;try{return JSON.parse(m[1]);}catch(e){return null;}}
function iframeFrom(html,base){var m=String(html||"").match(/<iframe\s[^>]*\bsrc=["']([^"']+)["']/i);return m?abs(base,m[1]):"";}
function maxQuality(body){var max=0,m,re=/RESOLUTION=\d+x(\d+)/gi,s=String(body||"");while((m=re.exec(s))!==null)max=Math.max(max,parseInt(m[1],10)||0);return max?max+"p":"Auto";}
function resolveOuter(base,id,type,season,episode){var outer=embed(base,id,type,season,episode);return fetch(outer,{headers:h()}).then(function(r){if(!r.ok)throw new Error("outer "+r.status);return r.text();}).then(function(outerHtml){var inner=iframeFrom(outerHtml,outer);if(!inner)return{html:outerHtml,ref:outer};return fetch(inner,{headers:h(outer)}).then(function(r){if(!r.ok)throw new Error("inner "+r.status);return r.text();}).then(function(html){return{html:html,ref:inner};});}).then(function(ctx){var c=configFrom(ctx.html);if(!c||!c.streamDataApiUrl||!c.mediaId)throw new Error("CONFIG missing");var api=c.streamDataApiUrl+"?"+(c.idType==="imdb"?"imdb=":"tmdb=")+encodeURIComponent(c.mediaId)+"&type="+encodeURIComponent(c.mediaType||type);if((c.mediaType||type)==="tv")api+="&season="+encodeURIComponent(c.season||season||1)+"&episode="+encodeURIComponent(c.episode||episode||1);return fetch(api,{headers:h(ctx.ref)}).then(function(r){if(!r.ok)throw new Error("api "+r.status);return r.json();}).then(function(j){var d=j&&j.data?j.data:null;var urls=d&&Array.isArray(d.stream_urls)?d.stream_urls:[];return Promise.all(urls.map(function(u,idx){u=clean(u);if(!/^https?:\/\//i.test(u))return Promise.resolve(null);return fetch(u,{headers:h(ctx.ref)}).then(function(r){if(!r.ok)throw new Error("hls "+r.status);return r.text();}).then(function(body){var q=maxQuality(body);var name="OnlyFlix · Server 1 · VidAPI · "+(idx===0?q:"Source "+(idx+1));return{name:name,title:name,url:u,quality:q,type:"hls",provider:"onlyflix-vidapi",headers:{"User-Agent":UA,"Referer":ctx.ref},subtitles:[]};}).catch(function(){var name="OnlyFlix · Server 1 · VidAPI · Source "+(idx+1);return{name:name,title:name,url:u,quality:"Auto",type:"hls",provider:"onlyflix-vidapi",headers:{"User-Agent":UA,"Referer":ctx.ref},subtitles:[]};});})).then(function(x){return x.filter(Boolean);});});});}
function tryOuter(i,id,type,season,episode){if(i>=OUTERS.length)return Promise.resolve([]);return resolveOuter(OUTERS[i],id,type,season,episode).then(function(x){return x.length?x:tryOuter(i+1,id,type,season,episode);}).catch(function(){return tryOuter(i+1,id,type,season,episode);});}
function getStreams(tmdbId,mediaType,season,episode){if(!tmdbId||(mediaType!=="movie"&&mediaType!=="tv"))return Promise.resolve([]);if(mediaType==="tv"&&(!season||!episode))return Promise.resolve([]);return tryOuter(0,tmdbId,mediaType,season,episode).then(function(rows){var out=[],seen={};(rows||[]).forEach(function(x){if(x.url&&!seen[x.url]){seen[x.url]=1;out.push(x);}});console.log("[OnlyFlix/VidAPI] "+mediaType+" "+tmdbId+" streams="+out.length);return out;}).catch(function(e){console.error("[OnlyFlix/VidAPI] "+(e&&e.message?e.message:e));return[];});}
module.exports={getStreams:getStreams};